{% set name = "boa" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/boa/archive/{{ version }}.tar.gz
  sha256: 798c9dcf550baa9109278938355edf3bf7ad4459b86d5af64ccd71635b02f6ee

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  noarch: python
  entry_points:
    - conda-mambabuild = boa.cli.mambabuild:main
    - boa = boa.cli.boa:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - conda-build >=3.24
    - libmambapy >=1.5,<1.6
    - ruamel.yaml >=0.18.0
    - jinja2
    - rich
    - prompt_toolkit
    - json5
    - jsonschema
    - joblib
    - watchgod
    - beautifulsoup4

test:
  imports:
    - boa
    - boa.cli
  commands:
    - boa -h

about:
  home: https://github.com/mamba-org/boa
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The mamba-powered conda package builder

extra:
  recipe-maintainers:
    - wolfv
    - JohanMabille
    - isuruf
    - mbargull
