{% set name = "boa" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/boa/archive/{{ version }}.tar.gz
  sha256: aeec58c0c200d350a4f0dd0aa0d9108998054be54378db87676cabba67cf149c

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  noarch: python
  entry_points:
    - conda-mambabuild = boa.cli.mambabuild:main
    - boa = boa.cli.boa:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - conda-build >=3.20,<3.24
    - mamba >=1.0,<1.3
    - ruamel.yaml
    - jinja2
    - rich
    - prompt_toolkit
    - json5
    - jsonschema
    - joblib
    - watchgod
    # for python 3.6 compatibility
    - dataclasses

test:
  imports:
    - boa
    - boa.cli
  commands:
    - boa -h

about:
  home: https://github.com/mamba-org/boa
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The mamba-powered conda package builder

extra:
  recipe-maintainers:
    - wolfv
    - JohanMabille
    - isuruf
