{% set name = "boa" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/boa/archive/{{ version }}.tar.gz
  sha256: d2c9d6747f2495759e6807d46b02050f1e7e4adb38999fd23256c271bef34011

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 1
  noarch: python
  entry_points:
    - conda-mambabuild = boa.cli.mambabuild:main
    - boa = boa.cli.boa:main

requirements:
  build:
    - python >=3.6                           # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - conda-build >=3.20,<3.22
    - mamba >=0.21.0,<0.23
    - ruamel.yaml
    - jinja2
    - rich
    - prompt_toolkit
    - json5
    - jsonschema
    - joblib
    - watchgod
    # for python 3.6 compatibility
    - dataclasses

test:
  imports:
    - boa
    - boa.cli
  commands:
    - boa -h

about:
  home: https://github.com/mamba-org/boa
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The mamba-powered conda package builder

extra:
  recipe-maintainers:
    - wolfv
